# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db1e81805ca296685e787074e2bdb6312aa8d292937f429719e2193f1df3ba9a056a63abdbb8812f4ca8ef42aa8a6d670dabb449123552fd0e75dc0b0bde4e08

test:
  secret_key_base: 9afda8a72c5231f052c1065ddfe558bbae6b51d2367660ff5fbe4f85825bbfdbe6f615229e68cd9e3b04366a9566f2c34d9f7333367bea98f2105d1295d3c7b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
